baseurl = "https://example.org/"
languageCode = "en-us"
title = "Meet Mangukiya | meetmangukiya"
theme = "hugo-steam-theme"
disqusShortname = ""
# Enable Google Analytics be inserting your tracking code
googleAnalytics = "UA-86162389-3"
# Number of posts per page
paginate = 10

[params]
	title = "Meet Mangukiya | Blog"
	subtitle = "My footprint on the web."
	copyright = "Released under the MIT license."

	# You can choose between green, orange, red and blue.
	themecolor = "red"

	# Link custom assets relative to /static
	favicon   = "favicon.ico"
	customCSS = []
	customJS  = []

	# To provide some metadata for search engines and the about section in the footer
	# feel free to add a few information about you and your website.
	name = "Meet Mangukiya"
	bio = "programmer - student"
	description = ""

	# Link your social networks (optional)
	location = "Mumbai, Maharashtra, India"
	twitter = "meetmangukiya98"
	linkedin = ""
	googleplus = ""
	facebook = ""
	instagram = ""
	github = "meetmangukiya"
	gitlab = "meetmangukiya"
	bitbucket = ""

	# Customize or translate the strings
	keepReadingStr = "Keep reading"
	backtotopStr = "Back to top"
	shareStr = "Share"
	pageNotFoundTitle = "404 - Page not found"
